@baseUrl = http://localhost:3000/api


GET {{baseUrl}} HTTP/1.1

###
PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
    "username": "julis",
    "email": "julis@example.com",
    "birthdate": "1990-02-12",
    "first_name": "Fake",
    "last_name": "Julis",
    "password": "Pass123@"
}

###
POST  {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"lajos@example.com",
    "password":"Pass123@"
}

###

GET  {{baseUrl}}/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiY201bzd3cTdwMDAwMDExeHlhenB3eW9rcyIsImVtYWlsIjoiam9zc2huZG9kZGRAZGRleGFtcGxlLmNvbSJ9LCJpYXQiOjE3Mzc5MDcyMDAsImV4cCI6MTczOTYzNTIwMH0.4vrV8THTf4dJi0SyjtApwFDwBZMFsS9ixiGePyTyHnmOmJ_ObPhBbi7U4AIHsC7tOBVXXnnIFLyUCRR8cn6LrQ

###


GET  {{baseUrl}}/user/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiY201bzVpMm5tMDAwMHd6aGg1YTBmNTI2NSIsImVtYWlsIjoiam9zc2huZG9kZGRAZGRleGFtcGxlLmNvbSJ9LCJpYXQiOjE3MzY0MTI1NTEsImV4cCI6MTczODE0MDU1MX0.WmJngBn4j_BZ5_vA621LszGQBLDJbFTo45fi2TTzlwcgqiFuslKTv7gHJqq1_yMN8QzqqJdV5ln5xPz2qsMhlw

###


GET  {{baseUrl}}/user/verifyEmail?id=cm5o7wq7p000011xyazpwyoks&email=josshndoddd@ddexample.com HTTP/1.1

###

PUT  {{baseUrl}}/server/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTI4MDg0NiwiZXhwIjoxNzQzMDA4ODQ2fQ.dCd4dGhYwl3SfWTqJ1S8-_x7Wj1Gm9mGuj-0RlK0Wde3BqgBp3c6lAkjdzaC3-SxcO45mi4Rzia1F6sKmKnM8Q
Content-Type: application/json

{
    "name":"Lajoska szerverkéje",
    "picture": "https://preview.redd.it/ot08x5mn9xk71.png?auto=webp&s=55dc457d26c3b79c805fd4068f98987fffec111d",
    "visibility":"public"
}


###

GET  {{baseUrl}}/server/cm7xlp3xn0000ia0jk7pyi8a9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTk3MTAzNSwiZXhwIjoxNzQzNjk5MDM1fQ.cHBbomaMXwx1do_8LcASQnkMWyQKq4AiDHUpRMF1NsQU_gfELhkrvqP3WWcYm-R6NRyTydTqOubBS5dcoaEytA

###
PUT  {{baseUrl}}/server/invite/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTI4MDg0NiwiZXhwIjoxNzQzMDA4ODQ2fQ.dCd4dGhYwl3SfWTqJ1S8-_x7Wj1Gm9mGuj-0RlK0Wde3BqgBp3c6lAkjdzaC3-SxcO45mi4Rzia1F6sKmKnM8Q
Content-Type: application/json

{
    "lifetime": 99999000,
    "server_id":"cm7xlp3xn0000ia0jk7pyi8a9"
}


###
GET  {{baseUrl}}/server/invite/cm7xlqct00003ia0jn5k6u73p HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTI4MDg0NiwiZXhwIjoxNzQzMDA4ODQ2fQ.dCd4dGhYwl3SfWTqJ1S8-_x7Wj1Gm9mGuj-0RlK0Wde3BqgBp3c6lAkjdzaC3-SxcO45mi4Rzia1F6sKmKnM8Q

###

GET  {{baseUrl}}/token/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIiwidmVyaWZpY2F0aW9uX2NvZGUiOiJhc2QyIn0sImlhdCI6MTc0MjI0NDU5MCwiZXhwIjoxNzQzOTcyNTkwfQ._87NUnsZbPpuWzFLp8YC-HhJ4R_sDnnLb4lNgabyDq__Y14SKr-mUSQSA_YrAZZB3o2Hmb-dEHGMbiMyQ1Cv7Q
###
GET  {{baseUrl}}/user/servers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTk3MTAzNSwiZXhwIjoxNzQzNjk5MDM1fQ.cHBbomaMXwx1do_8LcASQnkMWyQKq4AiDHUpRMF1NsQU_gfELhkrvqP3WWcYm-R6NRyTydTqOubBS5dcoaEytA

###

#/server/:serverID/rooms/
GET  {{baseUrl}}/server/cm7xlp3xn0000ia0jk7pyi8a9/rooms HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTk3MTAzNSwiZXhwIjoxNzQzNjk5MDM1fQ.cHBbomaMXwx1do_8LcASQnkMWyQKq4AiDHUpRMF1NsQU_gfELhkrvqP3WWcYm-R6NRyTydTqOubBS5dcoaEytA

###
#/server/:serverID/rooms/
PUT {{baseUrl}}/server/cm7xlp3xn0000ia0jk7pyi8a9/chatgroups/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyIjp7ImlkIjoiY203dWRwZzV5MDAwMDJmNmpqZzRnMWJlbCIsImVtYWlsIjoibGFqb3NAZXhhbXBsZS5jb20iLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6Imxham9zIn0sImlhdCI6MTc0MTk3MTAzNSwiZXhwIjoxNzQzNjk5MDM1fQ.cHBbomaMXwx1do_8LcASQnkMWyQKq4AiDHUpRMF1NsQU_gfELhkrvqP3WWcYm-R6NRyTydTqOubBS5dcoaEytA
Content-Type: application/json

{
    "name":"Hi"
}

###