@baseUrl = http://localhost:3000/api

PUT {{baseUrl}}/user HTTP/1.1
Content-Type: application/json

{
    "username": "Jegggg",
    "email": "johndoddde@xample.com",
    "birthdate": "1990-02-12",
    "first_name": "Jsssn",
    "last_name": "sss",
    "password": "sssaasD3#ss"
}

###
POST  {{baseUrl}}/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"johndodddexampl@e.com",
    "password":"pasaSas#d1"
}

###

GET  {{baseUrl}}/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiY201NTh0ZmlkMDAwMHhyN3FvbjJmcXI4biIsImVtYWlsIjoiam9obmRvZGRkZXhhbXBsQGUuY29tIn0sImlhdCI6MTczNTIyNTM3NywiZXhwIjoxNzM2OTUzMzc3fQ.0q2o713De1dikH_9Xte3vase8iHTItLXm2_gY1_Gm86SCzXqnGvw6DV1YD1MxlUfOCOpaisSQV3Ww9BcB7VrXQ

###

